[general]
start = "bun run dev"
cookbookPort = 8000

[projects.__test__]
port = 9000
type = "milkio"
typiaMode = "generation"
start = [
  "bun",
  "run",
  "--watch",
  "./runtime/bun.ts"
]
build = [
  "bun",
  "run",
  "./runtime/bun.ts"
]