[general]
start = "bun run dev"
cookbookPort = 8000

[projects.__test__]
port = 9000
type = "milkio"
typiaMode = "generation"
start = [
  "bun",
  "run",
  "--watch",
  "./runtime/bun.ts"
]
build = [
  "bun",
  "run",
  "./runtime/bun.ts"
]

[projects.cookbook-ui]
port = 8999
type = "other"
start = [
  "bun",
  "run",
  "dev"
]
build = [
  "bun",
  "run",
  ".milkio/bun-build.ts"
]
