#!/usr/bin/env bun

import { $ } from "bun";
import { join } from "node:path";
import { readFile } from "fs/promises";
import { exit, cwd } from "node:process";

await $`bun run typia generate --input src --output generated --project tsconfig.json`.cwd(join(cwd(), "packages", "cookbook-parser"));
let cookbookParser = (await readFile(join(cwd(), "packages", "cookbook-parser", "generated", "index.ts"))).toString();
cookbookParser =
  `/**
 * The content of this file is automatically generated by Typia.
 * It can be edited in the /packages/cookbook-parser/src/index.ts file, and each time you run bun run dev, the generated file will be synced to another location based on the content of the /develop.ts.
 */\n` + cookbookParser;
const writePaths = [join(cwd(), "packages", "cookbook", "src", "utils", "cookbook-parser.ts")];

for (const writePath of writePaths) {
  await Bun.write(writePath, cookbookParser);
}

await $`bun i`;
await $`chmod +x ./node_modules/.bin/cookbook`;
await $`cd ./packages/cookbook/ && bun i`;
