/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Linking: typeof import('./src/components/linking.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
  }
}
